### PR TITLE
Player 3503

### PR DESCRIPTION
**Pull request by aeng7**

### CODE REVIEW

**Comment by aeng7** [comment]
Do not merge yet, need to sync up with Steve and the analytics team

**Comment by aeng7** [comment]
This also does not do anything until the analytics team pushes the updated IQ JS SDK to prod

**Comment by aeng7** [comment]
After this is merged, I'll need to update the submodule in mjolnir

**Comment by aeng7** [comment]
We can merge now. Confirmed with Steve.

**Comment by pilievOoyala** [comment]
LGTM.

**Pull request merged**
