### PR TITLE
[PBF-661] Adds encoding for Akamai live/remote for secure tokens.

### PR DESCRIPTION
**Pull request by brianfwong**

### CODE REVIEW

**Comment by pilievOoyala** [comment]
What does this checkin do?  It's changing the latest commit of the submodule and then changing it back to the original.  So there is no point in committing this.

**Comment by brianfwong** [comment]
I don't know why, but there is a QA modules auto-update to this pull request that undid the needed change.
I'll put the change back in.

**Comment by brianfwong** [comment]
@agunawan @bobooyala PBF-661 - updates to use new html5-common, which has new constant for HD2, needed by akamai and analytics. Keeps submodules consistent across repos.

For some reason QA Tools / Jenkins auto reverted this update earlier...

**Comment by chibzu** [comment]
👍

**Pull request merged**
